export const DRUG_CATEGORIES = {
  ANTIBIOTICS: 'antibiotics',
  PAINKILLERS: 'painkillers',
  VITAMINS: 'vitamins',
  SUPPLEMENTS: 'supplements',
  PRESCRIPTION: 'prescription',
  OTC: 'otc',
  OTHER: 'other',
} as const;

export type DrugCategory = typeof DRUG_CATEGORIES[keyof typeof DRUG_CATEGORIES];

export const DRUG_CATEGORY_LABELS = {
  [DRUG_CATEGORIES.ANTIBIOTICS]: 'Antibiotics',
  [DRUG_CATEGORIES.PAINKILLERS]: 'Painkillers',
  [DRUG_CATEGORIES.VITAMINS]: 'Vitamins',
  [DRUG_CATEGORIES.SUPPLEMENTS]: 'Supplements',
  [DRUG_CATEGORIES.PRESCRIPTION]: 'Prescription',
  [DRUG_CATEGORIES.OTC]: 'Over the Counter',
  [DRUG_CATEGORIES.OTHER]: 'Other',
} as const;

export const DRUG_CATEGORY_OPTIONS = [
  { value: DRUG_CATEGORIES.ANTIBIOTICS, label: DRUG_CATEGORY_LABELS[DRUG_CATEGORIES.ANTIBIOTICS] },
  { value: DRUG_CATEGORIES.PAINKILLERS, label: DRUG_CATEGORY_LABELS[DRUG_CATEGORIES.PAINKILLERS] },
  { value: DRUG_CATEGORIES.VITAMINS, label: DRUG_CATEGORY_LABELS[DRUG_CATEGORIES.VITAMINS] },
  { value: DRUG_CATEGORIES.SUPPLEMENTS, label: DRUG_CATEGORY_LABELS[DRUG_CATEGORIES.SUPPLEMENTS] },
  { value: DRUG_CATEGORIES.PRESCRIPTION, label: DRUG_CATEGORY_LABELS[DRUG_CATEGORIES.PRESCRIPTION] },
  { value: DRUG_CATEGORIES.OTC, label: DRUG_CATEGORY_LABELS[DRUG_CATEGORIES.OTC] },
  { value: DRUG_CATEGORIES.OTHER, label: DRUG_CATEGORY_LABELS[DRUG_CATEGORIES.OTHER] },
]; 