export const LAB_TEST_CATEGORIES = {
  BLOOD_TESTS: 'BLOOD_TESTS',
  URINE_TESTS: 'URINE_TESTS',
  STOOL_TESTS: 'STOOL_TESTS',
  IMAGING_TESTS: 'IMAGING_TESTS',
  OTHER_TESTS: 'OTHER_TESTS',
} as const;

export const LAB_TEST_TYPES = {
  // Blood Tests
  COMPLETE_BLOOD_COUNT: 'COMPLETE_BLOOD_COUNT',
  BLOOD_GLUCOSE: 'BLOOD_GLUCOSE',
  LIPID_PROFILE: 'LIPID_PROFILE',
  LIVER_FUNCTION: 'LIVER_FUNCTION',
  KIDNEY_FUNCTION: 'KIDNEY_FUNCTION',
  THYROID_FUNCTION: 'THYROID_FUNCTION',
  HEMOGLOBIN: 'HEMOGLOBIN',
  WHITE_BLOOD_CELL_COUNT: 'WHITE_BLOOD_CELL_COUNT',
  PLATELET_COUNT: 'PLATELET_COUNT',
  
  // Urine Tests
  URINE_ANALYSIS: 'URINE_ANALYSIS',
  URINE_CULTURE: 'URINE_CULTURE',
  PREGNANCY_TEST: 'PREGNANCY_TEST',
  
  // Stool Tests
  STOOL_ANALYSIS: 'STOOL_ANALYSIS',
  STOOL_CULTURE: 'STOOL_CULTURE',
  
  // Imaging Tests
  X_RAY: 'X_RAY',
  ULTRASOUND: 'ULTRASOUND',
  ECG: 'ECG',
  
  // Other Tests
  MALARIA_TEST: 'MALARIA_TEST',
  TYPHOID_TEST: 'TYPHOID_TEST',
  HIV_TEST: 'HIV_TEST',
  HEPATITIS_TEST: 'HEPATITIS_TEST',
} as const;

export const LAB_TEST_LABELS = {
  [LAB_TEST_TYPES.COMPLETE_BLOOD_COUNT]: 'Complete Blood Count (CBC)',
  [LAB_TEST_TYPES.BLOOD_GLUCOSE]: 'Blood Glucose',
  [LAB_TEST_TYPES.LIPID_PROFILE]: 'Lipid Profile',
  [LAB_TEST_TYPES.LIVER_FUNCTION]: 'Liver Function Test',
  [LAB_TEST_TYPES.KIDNEY_FUNCTION]: 'Kidney Function Test',
  [LAB_TEST_TYPES.THYROID_FUNCTION]: 'Thyroid Function Test',
  [LAB_TEST_TYPES.HEMOGLOBIN]: 'Hemoglobin',
  [LAB_TEST_TYPES.WHITE_BLOOD_CELL_COUNT]: 'White Blood Cell Count',
  [LAB_TEST_TYPES.PLATELET_COUNT]: 'Platelet Count',
  [LAB_TEST_TYPES.URINE_ANALYSIS]: 'Urine Analysis',
  [LAB_TEST_TYPES.URINE_CULTURE]: 'Urine Culture',
  [LAB_TEST_TYPES.PREGNANCY_TEST]: 'Pregnancy Test',
  [LAB_TEST_TYPES.STOOL_ANALYSIS]: 'Stool Analysis',
  [LAB_TEST_TYPES.STOOL_CULTURE]: 'Stool Culture',
  [LAB_TEST_TYPES.X_RAY]: 'X-Ray',
  [LAB_TEST_TYPES.ULTRASOUND]: 'Ultrasound',
  [LAB_TEST_TYPES.ECG]: 'ECG',
  [LAB_TEST_TYPES.MALARIA_TEST]: 'Malaria Test',
  [LAB_TEST_TYPES.TYPHOID_TEST]: 'Typhoid Test',
  [LAB_TEST_TYPES.HIV_TEST]: 'HIV Test',
  [LAB_TEST_TYPES.HEPATITIS_TEST]: 'Hepatitis Test',
} as const;

export const LAB_TEST_CATEGORY_LABELS = {
  [LAB_TEST_CATEGORIES.BLOOD_TESTS]: 'Blood Tests',
  [LAB_TEST_CATEGORIES.URINE_TESTS]: 'Urine Tests',
  [LAB_TEST_CATEGORIES.STOOL_TESTS]: 'Stool Tests',
  [LAB_TEST_CATEGORIES.IMAGING_TESTS]: 'Imaging Tests',
  [LAB_TEST_CATEGORIES.OTHER_TESTS]: 'Other Tests',
} as const;

export const LAB_TEST_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export const LAB_TEST_STATUS_LABELS = {
  [LAB_TEST_STATUS.PENDING]: 'Pending',
  [LAB_TEST_STATUS.IN_PROGRESS]: 'In Progress',
  [LAB_TEST_STATUS.COMPLETED]: 'Completed',
  [LAB_TEST_STATUS.CANCELLED]: 'Cancelled',
} as const;

export const LAB_TEST_OPTIONS = Object.entries(LAB_TEST_LABELS).map(([value, label]) => ({
  value,
  label,
}));

export const LAB_TEST_CATEGORY_OPTIONS = Object.entries(LAB_TEST_CATEGORY_LABELS).map(([value, label]) => ({
  value,
  label,
})); 