export const PAYMENT_METHODS = {
  CASH: 'cash',
  CARD: 'card',
  MOBILE_MONEY: 'mobile_money',
  INSURANCE: 'insurance',
  BANK_TRANSFER: 'bank_transfer',
} as const;

export type PaymentMethod = typeof PAYMENT_METHODS[keyof typeof PAYMENT_METHODS];

export const PAYMENT_METHOD_LABELS = {
  [PAYMENT_METHODS.CASH]: 'Cash',
  [PAYMENT_METHODS.CARD]: 'Card',
  [PAYMENT_METHODS.MOBILE_MONEY]: 'Mobile Money',
  [PAYMENT_METHODS.INSURANCE]: 'Insurance',
  [PAYMENT_METHODS.BANK_TRANSFER]: 'Bank Transfer',
} as const;

export const PAYMENT_METHOD_OPTIONS = [
  { value: PAYMENT_METHODS.CASH, label: PAYMENT_METHOD_LABELS[PAYMENT_METHODS.CASH] },
  { value: PAYMENT_METHODS.CARD, label: PAYMENT_METHOD_LABELS[PAYMENT_METHODS.CARD] },
  { value: PAYMENT_METHODS.MOBILE_MONEY, label: PAYMENT_METHOD_LABELS[PAYMENT_METHODS.MOBILE_MONEY] },
  { value: PAYMENT_METHODS.INSURANCE, label: PAYMENT_METHOD_LABELS[PAYMENT_METHODS.INSURANCE] },
  { value: PAYMENT_METHODS.BANK_TRANSFER, label: PAYMENT_METHOD_LABELS[PAYMENT_METHODS.BANK_TRANSFER] },
]; 