export const SALE_PAYMENT_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
} as const;

export const SALE_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export const SALE_PAYMENT_STATUS_LABELS = {
  [SALE_PAYMENT_STATUS.PENDING]: 'Pending',
  [SALE_PAYMENT_STATUS.COMPLETED]: 'Completed',
  [SALE_PAYMENT_STATUS.FAILED]: 'Failed',
  [SALE_PAYMENT_STATUS.REFUNDED]: 'Refunded',
} as const;

export const SALE_STATUS_LABELS = {
  [SALE_STATUS.PENDING]: 'Pending',
  [SALE_STATUS.COMPLETED]: 'Completed',
  [SALE_STATUS.CANCELLED]: 'Cancelled',
} as const;

export const SALE_PAYMENT_STATUS_OPTIONS = [
  { value: SALE_PAYMENT_STATUS.PENDING, label: SALE_PAYMENT_STATUS_LABELS[SALE_PAYMENT_STATUS.PENDING] },
  { value: SALE_PAYMENT_STATUS.COMPLETED, label: SALE_PAYMENT_STATUS_LABELS[SALE_PAYMENT_STATUS.COMPLETED] },
  { value: SALE_PAYMENT_STATUS.FAILED, label: SALE_PAYMENT_STATUS_LABELS[SALE_PAYMENT_STATUS.FAILED] },
  { value: SALE_PAYMENT_STATUS.REFUNDED, label: SALE_PAYMENT_STATUS_LABELS[SALE_PAYMENT_STATUS.REFUNDED] },
];

export const SALE_STATUS_OPTIONS = [
  { value: SALE_STATUS.PENDING, label: SALE_STATUS_LABELS[SALE_STATUS.PENDING] },
  { value: SALE_STATUS.COMPLETED, label: SALE_STATUS_LABELS[SALE_STATUS.COMPLETED] },
  { value: SALE_STATUS.CANCELLED, label: SALE_STATUS_LABELS[SALE_STATUS.CANCELLED] },
];

export type SalePaymentStatus = typeof SALE_PAYMENT_STATUS[keyof typeof SALE_PAYMENT_STATUS];
export type SaleStatus = typeof SALE_STATUS[keyof typeof SALE_STATUS]; 