export const clerkConfig = {
  appearance: {
    elements: {
      formButtonPrimary: 'bg-blue-600 hover:bg-blue-700 text-white',
      card: 'w-full bg-transparent shadow-none',
      headerTitle: 'text-gray-100 text-xl font-semibold',
      headerSubtitle: 'text-gray-400',
      formFieldInput: 'border border-gray-600 bg-gray-800 text-gray-100 placeholder:text-gray-400 focus:border-blue-500 focus:ring-blue-500',
      formFieldLabel: 'text-gray-300 font-medium',
      footerActionLink: 'text-blue-400 hover:text-blue-300',
      dividerLine: 'bg-gray-600',
      dividerText: 'text-gray-400',
      socialButtonsBlockButton: 'border border-gray-600 bg-gray-800 text-gray-300 hover:bg-gray-700',
      formFieldInputShowPasswordButton: 'text-gray-400 hover:text-gray-300',
      formResendCodeLink: 'text-blue-400 hover:text-blue-300',
      footerAction: 'text-gray-400',
      formFieldRow: 'space-y-4',
      formField: 'space-y-2',
      form: 'space-y-4',
      header: 'text-center mb-6',
      footer: 'text-center mt-6',
      rootBox: 'w-full',
    },
    variables: {
      colorPrimary: '#3b82f6',
      colorText: '#f1f5f9',
      colorTextSecondary: '#cbd5e1',
      colorBackground: '#0f172a',
      colorInputBackground: '#1e293b',
      colorInputText: '#f1f5f9',
      colorNeutral: '#9ca3af',
      colorSuccess: '#22c55e',
      colorDanger: '#f87171',
      colorWarning: '#fbbf24',
    }
  },
  publishableKey: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
  signInUrl: "/sign-in",
  signUpUrl: "/sign-up",
  afterSignInUrl: "/dashboard",
  afterSignUpUrl: "/dashboard",
  redirectUrl: "/dashboard",
};