export const clerkConfig = {
  appearance: {
    elements: {
      formButtonPrimary: 'bg-blue-600 hover:bg-blue-700 text-white',
      card: 'w-full bg-transparent shadow-none',
      headerTitle: 'text-gray-900 text-xl font-semibold',
      headerSubtitle: 'text-gray-600',
      formFieldInput: 'border border-gray-300 bg-white text-gray-900 placeholder:text-gray-500 focus:border-blue-500 focus:ring-blue-500',
      formFieldLabel: 'text-gray-700 font-medium',
      footerActionLink: 'text-blue-600 hover:text-blue-500',
      dividerLine: 'bg-gray-200',
      dividerText: 'text-gray-500',
      socialButtonsBlockButton: 'border border-gray-300 bg-white text-gray-700 hover:bg-gray-50',
      formFieldInputShowPasswordButton: 'text-gray-500 hover:text-gray-700',
      formResendCodeLink: 'text-blue-600 hover:text-blue-500',
      footerAction: 'text-gray-600',
      formFieldRow: 'space-y-4',
      formField: 'space-y-2',
      form: 'space-y-4',
      header: 'text-center mb-6',
      footer: 'text-center mt-6',
      rootBox: 'w-full',
    },
    variables: {
      colorPrimary: '#2563eb',
      colorText: '#111827',
      colorTextSecondary: '#6b7280',
      colorBackground: '#ffffff',
      colorInputBackground: '#ffffff',
      colorInputText: '#111827',
      colorNeutral: '#6b7280',
      colorSuccess: '#059669',
      colorDanger: '#dc2626',
      colorWarning: '#d97706',
    }
  },
  publishableKey: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
  signInUrl: "/sign-in",
  signUpUrl: "/sign-up",
  afterSignInUrl: "/dashboard",
  afterSignUpUrl: "/dashboard",
  redirectUrl: "/dashboard",
};